### ISSUE TITLE
Shaman Weakauras - Frost Shock

### ISSUE THREAD

**Issue by Darkwave76** [Afenar/AfenarUI#102]
In enhancement you are missing to track frost shock.
It will be fairly easy to adapt your WA to do that because we are double tracking Fire Shock with two icons.
My suggestion is to change one of the two to track Frost Shock CD and use the other to track both CD and Duration.

**Comment by Wolfeg** [comment]
In middle bar (big icons) is debuff on target, on top left icon is shocks cooldown (fire and frost have same cd) there is just a fire icon, but it indicates frost cd too.
