### ISSUE TITLE
Soul Shard bar displaying as full constantly

### ISSUE THREAD

**Issue by SnakeYJ4** [Afenar/AfenarUI#111]
I only have 3 Shards (check the number in the middle) but the bar displays as if 5 are available.
![image](https://user-images.githubusercontent.com/116798825/205733595-4614fdf9-d8b2-462d-8866-401a3deef3ae.png)

**Comment by warrenwegs** [comment]
Similar issue for death knight runes 
![image](https://user-images.githubusercontent.com/13269162/206046643-4e590d15-bb30-4449-b4aa-d11d605b143f.png)

**Comment by warrenwegs** [comment]
Looks like a weak auras issue. Updating to the latest has fixed this for me
