### ISSUE TITLE
Dire beast charges with BM legendary shoulders

### ISSUE THREAD

**Issue by listara** [Afenar/AfenarUI#12]
Hey there. I'm wondering how to setup your weakauras for beastmastery hunters so it shows 2 charges on dire beast when I equip legendary BM shoulders. When I use one charge, it just shows me that it's on cooldown though I have 1 more charge left. Thanks in advance!

**Comment by Afenar** [comment]
Thanks, will add it today

**Comment by Afenar** [comment]
fxd

**Comment by listara** [comment]
Seems it doesn't work for me still :( 
http://imgur.com/a/w75Uy     -     got 1 charge up but WA shows CD ticking and no way to see this one charge available if I hide my actionbars

**Comment by Afenar** [comment]
Sry, refixed this(

**Comment by listara** [comment]
Thx, works perfect so far! :D

**Comment by Afenar** [comment]
whooohoo  ^_^
