### ISSUE TITLE
Problems with Balance Druid

### ISSUE THREAD

**Issue by hippostar** [Afenar/AfenarUI#13]
Hello,

I have been using this https://github.com/Afenar/AfenarUI/blob/master/DruidUI/Druid_Balance.txt for a couple of months now. Since 7.2 it spams LUA errors and the auras don't show up anymore.

I found one problem with Astral_Power_CastSpark Trigger 3 Duration Info line 4 is

`local myEnergyType = 'SPELL_POWER_INSANITY '             -- сюда свой тип энергии`

Changed it to

`local myEnergyType = SPELL_POWER_LUNAR_POWER            -- сюда свой тип энергии`

The errors are gone but the all of the Balance auras still doesn't show up. Its like they just dont load or something...

Can you have a look at this please?

**Comment by Afenar** [comment]
here's temporal decisions =\

**Comment by Afenar** [comment]
fixed
