### ISSUE TITLE
Hi! I have some problems!)) 

### ISSUE THREAD

**Issue by Mojo41reg** [Afenar/AfenarUI#17]
i never played wow and i don't have any idea what to do in this game. But i know you. Could you help me with it. Ваня, привет! Как дела у тебя)) как жена как дети? Тысячу лет не видел тебя! Ты как, на Камчатке живёшь еще или улетел может куда. С такими властями надо валить из России не то что с Камчатки =) 
Я тут на горизонте проживаю, я знаю, что ты жил тут. Может вечерком подойду пообщаемся. Блин, 5 лет почти не виделись It's awesome) вкачался Наверное, да?) быком стал=) 
Ладно, если что пиши. Буду рад встретиться.is it ok for you?)  Сафронов Никита ДВГТУ

**Comment by Afenar** [comment]
Lol. Not Bad :D Привет, Никитос, я переехал сейчас оч далеко :) мб спишимся в ВК\БлизардЭпп? Afenar#2323 или Afenar в вк. +79092365415 цифры), не, не бык :))

**Comment by Mojo41reg** [comment]
БлизардЭпп... Эм )) даже не знаю, что это )) ВК да меня там нет или утратил уже давно пароль. хз ) есть типа вотсапа что нибудь ? Переехал далеко .. Европа ? Азия ? =) блин блин блин

**Comment by Mojo41reg** [comment]
Курская область??? Да ладно ))

**Comment by Mojo41reg** [comment]
Что то СМС до тебя не доходят 
89147880496

**Comment by Gryphfin** [comment]
Ребят, ничего не имею против вашей дружбы, но я подписан на автора и все переписки пересылаются мне на мыло. Я думаю, что не мне одному.  Поаккуратней там с номерами телефонов.
