### ISSUE TITLE
Kingsbane not detected

### ISSUE THREAD

**Issue by theyellingmute** [Afenar/AfenarUI#20]
Ive tried with Outlaw and Subtely weapons but it seems the addon simply forgets about Kingsbane after you try using it. If i unequip the weapon and re-equip then it detects it but when you use it then it stops working

**Comment by Afenar** [comment]
will check it

**Comment by Afenar** [comment]
fxd, try it

**Comment by theyellingmute** [comment]
perfect, thank you! good response, this is why i recommend your settings to
everyone!
