### ISSUE TITLE
No Soul Harvest active buff Warlock 

### ISSUE THREAD

**Issue by beroost** [Afenar/AfenarUI#21]
Just wondering why the active buff on Soul Harvest was removed? Your most recent update to the warlock weak auras seemed like you took a lot of the auras away. Also when the dots were expiring before they shook a little, which was kind of a nice effect. 

Is there anyway I can get the old weak aura setup back?

Btw, your weak auras are awesome. I absolutely love them, I use them on all my characters. :) Keep up the good work

**Comment by Afenar** [comment]
This buff isnt removed, it's jist replaced to an extra group, cz this grup became larger. You just need to set ALL WA's, not just essental\specname, you shoud set up extra group too.

About Dots - there's new highlight effext, but if in you don't like this option - just use animation "custom"
