### ISSUE TITLE
Healer WAs

### ISSUE THREAD

**Issue by Kroxywuff** [Afenar/AfenarUI#22]
I know it's not an issue, but I would like to leave some feedback.

The previous iteration of the healer weakauras were so much better than what you have now. The ones currently don't display enough information for some specs (there are no totem timers for resto shaman).

**Comment by Afenar** [comment]
Btw i dont like last gigantic and full of placeholders version.
and there're totem timers for restorshamans on this totems aswell, totem timer replace ready icon in use, and read "read me" or commit comments - now timers are your problem, i just make spiral basic and your omniCC\addonskins make numbers.
