### ISSUE TITLE
Rogue Agonizing Poison Removed

### ISSUE THREAD

**Issue by theyellingmute** [Afenar/AfenarUI#24]
Just a heads up in case you didnt know, Agonizing poison is no longer in the game and has been replaced with Toxic blade, if you use the weak auras with this talent it still gives the warning of agonizing poison not applied

**Comment by Afenar** [comment]
i just fixed this, waited for 7.2.5

**Comment by Afenar** [comment]
i just cant synchronize changes becouse of issue 
"you might need to open a shell and debug the state of this repo"
