### ISSUE TITLE
Outlaw rogue UI issues

### ISSUE THREAD

**Issue by bopalop** [Afenar/AfenarUI#25]
![image](https://user-images.githubusercontent.com/29433895/27135989-e96db4be-50ce-11e7-874a-e250a49e8371.png)

Dreadblades doesn't show up until it's in use, shows cooling down but is not shown once spell is ready.

Marked for death doesn't show cooldown or when it is available, just shows the active time of the debuff on the target, making it hard to continue using marked for death through cooldown reduction abilities

**Comment by Afenar** [comment]
thanks, fixed
