### ISSUE TITLE
Arms Warrior - Execute proc from legendary not always showing up

### ISSUE THREAD

**Issue by bdestrempes** [Afenar/AfenarUI#26]
Execute icon not always activating with legendary ring procs. Sometimes it'll activate right away, most of the times a few seconds late, sometimes not at all. Could not identify the cause to replicate but it happens regularly during a standard rotation.

![execute](https://user-images.githubusercontent.com/1951578/27201881-505a1d42-51ed-11e7-86b0-1b7957c1a086.png)

**Comment by Afenar** [comment]
is this happening with leg ring?

**Comment by bdestrempes** [comment]
Yes

**Comment by Afenar** [comment]
fxd
