### ISSUE TITLE
Destruction Warlock Soul Shard Change

### ISSUE THREAD

**Issue by Bpsmooth** [Afenar/AfenarUI#27]
First off, thanks for all your hard work! I love all of these weak auras!

I was just letting you know that destruction warlock has a new soul shard system, where a player can earn partial soul shards. Currently the warlock soul shard weak aura only tracks full soul shards. So I just wanted to let you know about the change, in case you didnt know already. Thanks again for everything!

**Comment by Afenar** [comment]
there's no any good suggestion for destro new sh system, so i can't change this, if you have some new WA strings - please share
