### ISSUE TITLE
Landslide talent not showing for Enhancement Shamans

### ISSUE THREAD

**Issue by Bpsmooth** [Afenar/AfenarUI#29]
Currently, there is no weak aura for Landslide buff for enhancement shamans. Landslide is a talent, but it doesn't appear when I take the talent. It is a pretty important buff to keep track of.

Edit: No big rush to get this working. I made my own to match your layout. But it would be nice to add before your next big update to all of your weak auras.

**Comment by Afenar** [comment]
This buff must be 100% uptime without tracking, cz you must not let your rockbiter overcap, you just can add if you want ^_^
