### ISSUE TITLE
Arcane Mage

### ISSUE THREAD

**Issue by Reign28** [Afenar/AfenarUI#3]
Getting a constant "gun reloading" sound on various ability usage, such as blink.  Not sure how to disable it.

[edit] Figured out it was in Arcane Mage Extras, Presence of Mind 2.  It was playing the shotgun sound with every ability i used.  I think the intention was to only play it when the ability came off CD.

**Comment by Afenar** [comment]
ty, will fix it

**Comment by Enohla** [comment]
Hello Afenar, loving your work on WA's. I was asking myself how i can turn off the sound on the Arcane Spec Auras for Mage everytime i enter to combat. Much appreciated and TY for all your work. :)

**Comment by Afenar** [comment]
hi, fxd ^_^
