### ISSUE TITLE
Shadow Priest t20 Set Bonus

### ISSUE THREAD

**Issue by ghost** [Afenar/AfenarUI#31]
Is there a way to add the t20 insanity bonus on mind blast to the insanity bar? I'm a shadow priest main and I love your UI and have been using it since the start of Legion but it's hard sometimes to properly judge how much extra insanity I'm going to get from MB.

Thanks for taking your time to go through this and keep up the awesome work!

**Comment by Afenar** [comment]
hello, right now i cant make something like that, cz dunno how(

**Comment by ghost** [comment]
Ah, alright :( Thank you anyway!
