### ISSUE TITLE
Energy Bar 

### ISSUE THREAD

**Issue by saikenpwn** [Afenar/AfenarUI#32]
I really like your rogue / sub rogue wa´s, best one´s i´ve ever seen. But one Question is it possible to make them invisible out of combat but only if they are at 100%, means if i use feint while out of combat the energy bar should appear, when it is refrsehed to 100% it should dissapear again. I hope you understand what i mean. Because i got no clue how to manage it... but it should be really helpful for me. Big thanks

**Comment by Afenar** [comment]
there should be some lua triggers. cant do it by myself sry
