### ISSUE TITLE
Mind Flay Ticks

### ISSUE THREAD

**Issue by SugarPunch** [Afenar/AfenarUI#33]
Hey Afenar, first a thanks for your awesome work on my favourite weakaura collection and interface ui.
I'm just curious if it's possible to add ticks to the Castbar (surge) especially for the use of Mind Flay.
Since I will miss out on some insanity if I just use it on gcd I would like to have the ticks visible.

I could just use the elvui castbar instead but that won't fit to the rest of the ui then =((

**Comment by Afenar** [comment]
Hey, i dunno how to make ticks in WA castbar. and u shouldn't track it now
