### ISSUE TITLE
No DfA CD for rogue?

### ISSUE THREAD

**Issue by amik0** [Afenar/AfenarUI#34]
Hello. Just started to play subtlety rogue, loaded your auras "Rogue_Subtlety" and "Rogue_Essential", and don't see CD aura for "Death from Above" talent on main cooldowns section.

![no_dfa](https://user-images.githubusercontent.com/5760620/30678881-0e666014-9e9e-11e7-80ab-b907d2cfccbe.PNG)

I'm a noob rogue currently, but it seems as important CD with short duration and essential part of sub's rotation. Added it by myself, but it would be nice to have it out of the box :)

**Comment by Afenar** [comment]
u need to download all WAs in the folder
