### ISSUE TITLE
Final:evis won't work

### ISSUE THREAD

**Issue by Minorz** [Afenar/AfenarUI#39]
Hi, 
i really love your WA. i'm addicted to it on every characters i play.
but one little thing. I just updated the rogue's WA but the finaly;evis doesn't work : the improvement is not displayed. Do you know why (i'm bad with WA config).

And is it possible to add the Trick Of Trade cooldown ?

Thanks in advance !
Keep goin ! love that !

**Comment by Afenar** [comment]
everything is ok
https://i.imgur.com/esSGvjI.png
realy dunno, mb you WA addon is ood?

added tricks

**Comment by Minorz** [comment]
Dunno if u can take a minute to see if the LUA of the aura is good. I updated WA but still not displayin

{
    ["glow"] = false,
    ["text1FontSize"] = 10,
    ["cooldownTextEnabled"] = true,
    ["customText"] = "function()\n    local perc = select(17, UnitBuff(\"player\", \"Irrévocabilité : Éviscération\", nil, \"PLAYER\"))\n    if perc then\n        return \" \"..perc..\"%\"\n    end\n    return \"\"\nend",
    ["untrigger"] = {
    },
    ["anchorPoint"] = "CENTER",
    ["activeTriggerMode"] = 0,
    ["customTextUpdate"] = "update",
    ["url"] = "https://wago.io/SJLQKGjMM/4",
    ["actions"] = {
        ["start"] = {
            ["do_glow"] = false,
        },
        ["init"] = {
        },
        ["finish"] = {
            ["do_glow"] = false,
        },
    },
    ["useTooltip"] = false,
    ["animation"] = {
        ["start"] = {
            ["duration_type"] = "seconds",
            ["preset"] = "fade",
            ["type"] = "preset",
        },
        ["main"] = {
            ["duration_type"] = "seconds",
            ["type"] = "none",
        },
        ["finish"] = {
            ["duration_type"] = "seconds",
            ["type"] = "none",
        },
    },
    ["trigger"] = {
        ["rem"] = "10.5",
        ["spellId"] = "34914",
        ["ownOnly"] = true,
        ["names"] = {
            [1] = "Irrévocabilité : Eviscération",
        },
        ["custom_hide"] = "timed",
        ["type"] = "aura",
        ["subeventSuffix"] = "_CAST_START",
        ["subeventPrefix"] = "SPELL",
        ["event"] = "Health",
        ["countOperator"] = ">",
        ["debuffType"] = "HELPFUL",
        ["use_name"] = true,
        ["use_spellId"] = true,
        ["spellIds"] = {
            [1] = 197393,
        },
        ["remOperator"] = ">",
        ["showOn"] = "showOnActive",
        ["count"] = "0",
        ["name"] = "Toucher vampirique",
        ["unit"] = "player",
    },
    ["text1Containment"] = "OUTSIDE",
    ["progressPrecision"] = 0,
    ["text1Point"] = "TOP",
    ["text2FontFlags"] = "OUTLINE",
    ["height"] = 36,
    ["disjunctive"] = "any",
    ["load"] = {
        ["ingroup"] = {
            ["multi"] = {
            },
        },
        ["talent"] = {
            ["single"] = 21,
            ["multi"] = {
                [21] = true,
            },
        },
        ["spec"] = {
            ["single"] = 3,
            ["multi"] = {
                [1] = true,
                [3] = true,
            },
        },
        ["class"] = {
            ["single"] = "ROGUE",
            ["multi"] = {
            },
        },
        ["talent2"] = {
            ["multi"] = {
            },
        },
        ["use_realm"] = false,
        ["use_class"] = true,
        ["role"] = {
            ["multi"] = {
            },
        },
        ["faction"] = {
            ["multi"] = {
            },
        },
        ["pvptalent"] = {
            ["multi"] = {
            },
        },
        ["use_spec"] = true,
        ["race"] = {
            ["multi"] = {
            },
        },
        ["difficulty"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["yOffset"] = 82.999969482422,
    ["color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["text2Point"] = "CENTER",
    ["text2Containment"] = "INSIDE",
    ["text1Font"] = "Homespun",
    ["text1Color"] = {
        [1] = 1,
        [2] = 0.96078431372549,
        [3] = 0.41176470588235,
        [4] = 1,
    },
    ["stickyDuration"] = false,
    ["inverse"] = false,
    ["text2Color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["regionType"] = "icon",
    ["text2Font"] = "Friz Quadrata TT",
    ["text1FontFlags"] = "OUTLINE",
    ["text2FontSize"] = 24,
    ["anchorFrameType"] = "SCREEN",
    ["text2Enabled"] = false,
    ["text1"] = "%c",
    ["zoom"] = 0,
    ["additional_triggers"] = {
    },
    ["text2"] = "%p",
    ["auto"] = true,
    ["desaturate"] = false,
    ["id"] = "finality: evis",
    ["selfPoint"] = "CENTER",
    ["frameStrata"] = 2,
    ["width"] = 36,
    ["text1Enabled"] = true,
    ["icon"] = true,
    ["numTriggers"] = 1,
    ["xOffset"] = 39,
    ["init_started"] = 1,
    ["conditions"] = {
    },
    ["cooldown"] = true,
    ["parent"] = "Rogue_MainBar_AfenarUI",
}
