### ISSUE TITLE
Error importing Rogue_Subtlety.txt

### ISSUE THREAD

**Issue by kubetz** [Afenar/AfenarUI#4]
When I try to import Rogue_Subtlety.txt I am getting following error:

> Error deserializing ....Details\Libs\AceSerializer-3.0.lua:179: Supplied data misses AceSerializer teminator ('^^')

Other import were working for me so far.

Thanks for your great work!

**Comment by Afenar** [comment]
strange, jut coppied - everything is ok oO

**Comment by kubetz** [comment]
What version of WeakAuras are you using? I will get the same version and try to reproduce it.

**Comment by kubetz** [comment]
Issue was caused by WeakAuras. Updated to newest WA2 and the imports are working now. Thanks!
