### ISSUE TITLE
Fearl Druid Bleeds Tracker & Assassination Rogue Kingsbane Stacks and Damage

### ISSUE THREAD

**Issue by DAGADIIN** [Afenar/AfenarUI#40]
absolutely love your aura setups, wondering if you thought about adding 
bleed tracker for druid, see if the next rake rip or thrash is gonna be stronger then current one
kingsbane stack and damage tracker, where stacks post in chat and damage shows next to the icon?
  

thanks
DAGAN

**Comment by Afenar** [comment]
hello, i'd like to put in my auras in future, thanks

**Comment by DAGADIIN** [comment]
no thank you for the great auras

**Comment by Afenar** [comment]
may be you've found any auras which i could rework for my setup?

**Comment by DAGADIIN** [comment]
I know there are some ppl on wago.it that have but up auras with these things in them. Potato is the main one that comes to mind for the assassination things and I believe pawkets over at fluiddruid has done the snapshotting for the feral bleeds

**Comment by Afenar** [comment]
potato have "bad" auras without id for spells(

but i don't even see any reason for tracking 3 snapshots for a cat, it's not a MoP now i suppose, but will find some

**Comment by DAGADIIN** [comment]
the snapshotting isnt a huge thing, just a suggestion.
