### ISSUE TITLE
BM Hunter - Wild Call (Dire Beast Reset)

### ISSUE THREAD

**Issue by MalyXXX** [Afenar/AfenarUI#41]
Hi Afenar,

Love the Hunter setup, but is there any chance to make Dire beast pop up whenever the cd is reseted due to wild call passive? 

Many thanks
Matt
  
P.S
I should say its not much of an issue... :)

**Comment by Afenar** [comment]
you mean when the ability is getting out of cd so it should glowing whenever the cd is reseted by a wild call?

**Comment by Afenar** [comment]
wild call passive cannot be tracked wby anything, cz it's just gradual cooldown, and i don't have any events for this
