### ISSUE TITLE
Consecration Prot Paladin

### ISSUE THREAD

**Issue by beroost** [Afenar/AfenarUI#43]
Hey, sorry to open another issue and I'm not even sure if this is something that you intended or not.

For the consecration bar on the Prot Paladin weak auras, is the bar supposed to show when consecration is active as well? I know it greys out when you aren't standing in it, but is there a way that you can make it show how long the buff on the ground has left because the active time for consecration is different than the cooldown.
Thank you, great work on all the weak auras :)

**Comment by Afenar** [comment]
hello, thanks for a feedback, i'll take a look

**Comment by Afenar** [comment]
fxd with neat icon
