### ISSUE TITLE
Confusion on Setup

### ISSUE THREAD

**Issue by TonyDSanti** [Afenar/AfenarUI#44]
Hi Afenar, I saw your UI and I instantly wanted, I posted a similar message a few minutes ago on your post about it. I'm extremely confused on how to set up my UI like the one in your images with the .txt files in the UI pack. Idk what goes where or how to really set up any of it. I'm new to modifying my wow UI so it is really difficult to figure it out. Hope someone can help this UI noob.

Thanks in advanced!

**Comment by Afenar** [comment]
hello, just visit this link: http://www.wowinterface.com/downloads/info23773-AfenarUI.html download and follow the read me instructions
