### ISSUE TITLE
Affliction Warlock Corruption

### ISSUE THREAD

**Issue by Cranabon** [Afenar/AfenarUI#45]
Corruption is not showing any duration 
Edit: Since Warlock is the last class im leveling to 110, I just found out it shows the icon, if using the talent Absolute Corruption, don't know if it changes later, but without it, the duration doesnt show for me

**Comment by Afenar** [comment]
WA's made just for 110 lvl, there's a condition, but soon enough i'll change some stuf and everything should be showing.

**Comment by Afenar** [comment]
fixed
