### ISSUE TITLE
Warlock: Tormeted_Agony

### ISSUE THREAD

**Issue by coreyfellows** [Afenar/AfenarUI#48]
The main bar Tormented Agony has a couple issues:
a) The aura is looking for a buff on the player, it should be looking for a debuff on the target.
b) It isn't friendly with Soul of the Netherlord. If you have the ring and Siphon Life on the two auras load on top of eachother.

I'm not very good, so I couldn't find a fix for B. My workaround was to just disable the main on and enable the Tormented_Agony_T for all talent setups.

**Comment by Afenar** [comment]
Fixed to a debuff to a target.
will do something with a ring

**Comment by Afenar** [comment]
actually i do not have a ring and it's to hard for me combine all damn talents together with this buffs, lately mb i will get it and will do something, but still - just do optional stuff by yourself

**Comment by Afenar** [comment]
added some fixes, may be it will help
