### ISSUE TITLE
Shield Wall and Last Stand

### ISSUE THREAD

**Issue by Dmak11** [Afenar/AfenarUI#50]
I imported the most up to date warrior WA main bar. The Shield Wall and Last stand buff durations were at (0,0). Not at (23,-46) Last Stand, (69,-46), like the CD WA. Thought I would let you know that was why it was not working.

**Comment by Afenar** [comment]
it's strange, i've tested wago string and from here - https://i.imgur.com/tw0VCgo.png

**Comment by Afenar** [comment]
thank you, it's bugged from github, will fix it!
