### ISSUE TITLE
Druid - Emerald Dreamcatcher tracking

### ISSUE THREAD

**Issue by Xyrec** [Afenar/AfenarUI#51]
Wanted to let you know that the Druid HUD currently doesn't have a way to track how many stacks of Emerald Dreamcatcher you have - I'm no lua coder, but the easiest fix would probably be to add an if statement to the duration info in the WA "Astral_Power_StarSurge" that tracks whether you have 1 or 2 stacks of the buff you get, and then subtract either 5 or 10 from 40. And then as an added bonus, maybe add an extra weakaura to display your current stacks, and time left on the buff. :)

**Comment by Afenar** [comment]
hello, there're a lot of different legendary buffs that currently not shown etc, due to i have not got a lot of them, so everyone can easily add any buff you want to it and modify any aura like you want
thank you
