### ISSUE TITLE
Shaman: Ancestral guidance not showing when ready + Tidal waves are not tracked anymore

### ISSUE THREAD

**Issue by johnfriedrich** [Afenar/AfenarUI#52]
Hey,
just updated my resto shaman weakauras with your latest ones. Thanks for all that work!
However Tidal waves stacks (bubbles) and Ancestral guidance tracking (when not on cooldown) is kinda missing. Would be cool if you find a way to add it back.

Cheers, John

**Comment by Afenar** [comment]
Tidal waves now is a bar, as you can see, and ancestral guardiance is in utility bar now
