### ISSUE TITLE
Enhancement Shaman Overlap Issues

### ISSUE THREAD

**Issue by Bpsmooth** [Afenar/AfenarUI#53]
I just wanted to let you know that there are a couple overlap issues with enhancement shaman. https://i.imgur.com/jYTdlvi.png You can see the cooldown for earthen spike behind doom winds, in this screenshot. https://i.imgur.com/bsMxNdI.png And in this screenshot you can see feral spirits overlapping earthen spike.

**Comment by Afenar** [comment]
it's strange, cz i donot see any issues like that, may be you moved something or just haven't updated new version, but there isn't any issues now https://i.imgur.com/VSOZYei.png

**Comment by Bpsmooth** [comment]
I think I figured out the issue. I added the Totem Bar weak aura string that you have. But I don't think we need that weak aura string anymore, since you added those auras into the mainbar?
