### ISSUE TITLE
wolfs icon closed by another icon + suggestions

### ISSUE THREAD

**Issue by Wolfeg** [Afenar/AfenarUI#55]
![wowscrnshot_030218_061924](https://user-images.githubusercontent.com/4620273/36883703-d062aad4-1e0e-11e8-82d3-32d14b000944.jpg)
иконка времени действия волков закрыта иконкой включенных ветров.
и парочка предложений:
1. справа я добавил отслеживание дебаффа на цели от 4 кусков т21, если не мониторить его теряешь в дпсе прилично, как вариант конечно можно смотреть на дебаффы цели, но это не так удобно
2. в рейде + в бою если не включены ветра то подсвечивать их
3. на прок бурста можно добавить "подсветку кнопки" для пущей заметности

**Comment by Afenar** [comment]
1. потому что тех тотемов больше нету, они находятся в другом месте, нужно переставлять все ауры. т21 к сожалению нет, как на многих классах, поэтому тут самостоятельно, но что-нить подшаманю, не знал, что у шамана меняется ротация от дебафа на таргете
2. ветра серые если не врублены в последнем апдейте.
3.вкусовщина :), но сделаю свечение в первые 2 сек прока пока что
спасибо!
