### ISSUE TITLE
Lashing_Flames Id  are Wrong (Enh Shaman)

### ISSUE THREAD

**Issue by jeversonmelo** [Afenar/AfenarUI#57]
Lashing_Flames was using the wrong id, change ID  to 240842 and also need to clear the talents for the WA load

I also made some changes.

When Stormbringer is up, the stormstrike icon changes to Stormbringer
When the 2PC T21 is in up, the Rockbite icon changes
Feral Spirit: WA always active
Alpha Wolf: Wa shows when Buff is up (Feral Spirit Buff)

Ty for Good work;

https://i.gyazo.com/a0361b7b6bcd0e8d4d7b47484fe2b1ac.gif

**Comment by Afenar** [comment]
done, thanks
