### ISSUE TITLE
Secondary abilities that were merged into the main hub.

### ISSUE THREAD

**Issue by mrfreezyweezy** [Afenar/AfenarUI#59]
Hello. I have been using your weakauras for a long time. I had a quick question regarding some of the functionality. I just went through and updated most of my characters as they have not been updated in a few months. What I am noticing is that some secondary abilities are missing from the main hub until you put the ability on cool down. For example: On my mage. On the main hub I only see Ebon bolt, frozen orb, blizzard, incanters flow, and icy veins. Using abilities like frost nova, ice block and invisibility will put them underneath the main bar but it only shows their cooldown once i use it.  Also it is desaturated. I was wondering if this change was intentional or if i messed something up on my end? I have deleted the add on and erased everything in the WTF folder to try and start from scratch. No luck.

**Comment by Afenar** [comment]
i just moved all utilities into a main group
