### ISSUE TITLE
[Warlock] [Demonology] Imp timer disappears when combat ends

### ISSUE THREAD

**Issue by filliph** [Afenar/AfenarUI#64]
If you use Hand of Gul'dan to summon imps, and combat ends, the bars that displays the remaining timer of your Wild Imps disappears.

This is sub-optimal in open-world content, as you will need to look at your regular buff UI to find out how long your imps have left and determine whether you should pull the next mob with Implosion or not.

Is this possible to fix?

**Comment by Afenar** [comment]
just turn it from out of combat to always

**Comment by filliph** [comment]
How? I’m not super familiar with configuring WA, sorry.
