### ISSUE TITLE
Fire Mage - problem with Enhanced pyrotechnics and Heating up

### ISSUE THREAD

**Issue by adelisle** [Afenar/AfenarUI#65]
Hi!

Heating up should be prioritized over Enhanced pyrotechnics.

Steps:
Get a Hot Streak! but don't use it yet.
Use Fireball to get Enhanced pyrotechnics up.
Use Hot Streak!
If it didn't crit, use Fire blast.

You should then have Enhanced pyrotechnics and Heating up showing up at the same time, with Enhanced pyrotechnics getting prioritized over Heating up.

I tried to configure the strate differently but it didn't work.

Thanks!

**Comment by Afenar** [comment]
Ehm, it's already prioritized over the Ench pyro

**Comment by adelisle** [comment]
I updated the WeakAura group from your latest and I still get the problem.

Please see attached screenshot.
![wowscrnshot_073018_183014](https://user-images.githubusercontent.com/41878227/43427409-5d73ea80-9427-11e8-8d90-e209da88cce2.jpg)

**Comment by Afenar** [comment]
fixed, thanks!
