### ISSUE TITLE
Pistol Shot and Ghostly Strike interaction issuesframe strata & position issues

### ISSUE THREAD

**Issue by mezmor** [Afenar/AfenarUI#68]
Issues:
- Frame strata
- Position

Their order in the WA list:
- Pistol_Shot
- Ghostly_Strike_B
- Ghostly_Strike

Frame Strata:
- Pistol Shot Frame Strata: BACKGROUND
- Ghostly_Strike_B Frame Strata: BACKGROUND
- Ghostly_Strike Frame Strata: LOW

(X, Y) Positions:
- Pistol_Shot: (0, 0)
- Ghostly_Strike_B: (0, 0)
- Ghostly_Strike: (0, 0)

The auras have the following states (may be missing a few, only checked by testing, not aura configuration inspection):
Ghostly Strike:
- unavailable to cast: not enough energy
- off cooldown
- on cooldown with debuff on target
- on cooldown

Pistol_Shot:
- Opportunity proc not active / buff not present.
- Opportunity proc active / buff present.

Default behaviors:
With Opportunity proc active and Ghostly Strike off cooldown, the Pistol_Shot glowing frame animation is only barely visible behind the Ghostly_Strike auras.

With Opp. proc active and GSunavailable to cast: not enough energy, there are some blending issues and the aura icons look confusing & unclear.

With Opp. proc active and GS on cooldown with debuff on target, it's impossible to tell that the Opportunity proc is active because the Ghostly Strike debuff frame glow overrides Pistol_Shots.

These are all suboptimal interactions. 

Most intuitive fix is to set set Pistol_Shot Frame Strata to Medium. This works for the most important case when Opp. proc is active, however there are other issues:
With Opp. proc not active and GS off cooldown, you get weird blending issues.

The blending issues occur even if GS is on cooldown, with or without debuff.

I'm not sure what the most optimal fix is... the easiest fix is probably to move one of the auras, but I don't know where to.

**Comment by Afenar** [comment]
what is the problem exactly  behavior? or you just cannot understand what's for these settings?

Opportunity proc is in the blizz allert and energy color: https://i.imgur.com/wR5E5Uf.jpg

if you need something else - do whatever you need to get more comfortable for you

**Comment by mezmor** [comment]
It does indeed show on the energy color. The problem with that is during Adrenaline Rush, the same energy color is used.

Also, there's no use for the golden icon highlight if the intent is to use energy color as the indicator.

**Comment by mezmor** [comment]
Speaking of which, how do I disable the energy bar from changing color on Opportunity proc? It's not Pistol_shot that's controlling that.

**Comment by Afenar** [comment]
I've added an icon if you don't use bizz auras somehow
