### ISSUE TITLE
Tooltip above Details!

### ISSUE THREAD

**Issue by Minorz** [Afenar/AfenarUI#69]
Hi

When i disabled tooltip with Elvui de default tooltip are above the details! window.
Whez is the positionning by default ?

Thx
love ur jobs (maybe cooldowns are too tiny now ?)

**Comment by Afenar** [comment]
hello, thanks.
Read readme, there's told, that you should turn of elvui tooltip, I'm using tipTac

Cooldowns are fine, if you want bigger - make them bigger

**Comment by Minorz** [comment]
Ok
thx love
Tiptac is not in the folder you updated on wowinterface

**Comment by Afenar** [comment]
it was out of date, so you can download it via the curse =\ sorry
