### ISSUE TITLE
Vehicle Bar Not Showing

### ISSUE THREAD

**Issue by Incarceron** [Afenar/AfenarUI#72]
I'm not sure how to get the vehicle bar to appear correctly. I've been messing with the ElvUI settings and can't seem to find anything other than in Shadow & Light there is an enhanced vehicle bar but I don't think that's what I'm looking for. Any help at all would be appreciated.

**Comment by Minorz** [comment]
Hi love,
here tou go : Elvui options > Shadow and Ligh > Modules > Enhanced Vehicule Bar
Then reload Ui
