### ISSUE TITLE
Shaman Maelstrom bar bug

### ISSUE THREAD

**Issue by ImBlueflash** [Afenar/AfenarUI#74]
Hi Afenar, Whenever I go afk or simply hide my UI by using alt+z for example my maelstrom bar background effect seems to disappear and only comes back when I open up /wa again I have no idea why it's doing this any idea? Screenshots as example : Here is the bugged maelstrom bar https://gyazo.com/7b53e31d257b764c798d1a38dd9fed0a, and here is how it should be: https://gyazo.com/4ecc07fc63fa07e7f02a16d53aa13343. Thanks in advance !

**Comment by Afenar** [comment]
it's WA bug, not mine, sorry
