### ISSUE TITLE
Bug regarding Thrash

### ISSUE THREAD

**Issue by VerySvensk** [Afenar/AfenarUI#75]
I do not know what caused it or what changed but Thrash does no longer show up in Guardian. The counter is there, the icon is fully loaded but thrash just does not pop up. 

Anybody else having the same issues? 

https://imgur.com/a/oFUSCBE

Here's a screenshot. And i'm using the latest version

**Comment by Afenar** [comment]
For such stuff you can join our discord https://discord.gg/cZVCTwB
