### ISSUE TITLE
Druid Balance Lunar/Solar 

### ISSUE THREAD

**Issue by VerySvensk** [Afenar/AfenarUI#78]
The Lunar / Solar Empowerment sometimes stops working between bosses and Combat. 

I haven't been able to reproduce it properly but after a boss in Uldur it just stops working

**Comment by Afenar** [comment]
1. Udpate WA to the latest version.
2. Update Pack to a latest one
3. https://i.imgur.com/Qi1l2zi.gifv all work fine, this empowerments fading when you are out of moonking form.
4. we have a discord
