### ISSUE TITLE
[DH] Momentum Buff

### ISSUE THREAD

**Issue by Gabb1995** [Afenar/AfenarUI#79]
Momentum buff doesn't show since latest update, the felrush buff not the vengeful retreat one.

**Comment by Afenar** [comment]
1. This bar is a momentum: https://i.imgur.com/nCkqAbx.gifv and this works
2. you see the same ID on a screen https://i.imgur.com/V9uTiQu.png
3. We have a discord

**Comment by Gabb1995** [comment]
ah, my bad then, didnt realise there was a bar (I have something else over there). Thanks.
