### ISSUE TITLE
Shaded out WA

### ISSUE THREAD

**Issue by Memnoch1** [Afenar/AfenarUI#83]
Hi,  I am having trouble with using this with elvui.  All of the Aura's and bars are shaded out  for me.  They are light up normal when I go into edit mode but as soon as I exit, they revert back to being shaded out.  I have tried uninstalling the addonskins package but cant seem to get it to work.  Any ideas?

![screenshot 2019-02-13 00 21 36](https://user-images.githubusercontent.com/47580692/52677347-6ec1c980-2f25-11e9-9e27-8c106d67e2e1.png)
![screenshot 2019-02-13 00 22 03](https://user-images.githubusercontent.com/47580692/52677352-71bcba00-2f25-11e9-9b00-b3801c847a84.png)

The first image is normal, the second is in edit mode.

**Comment by Gabb1995** [comment]
its on purpose, you have to go in combat for them to light up.

**Comment by Alarzzf** [comment]
Hi, can you continue to support WA?
I don't want to use OmniCC.
Because using OmniCC will cause some problems with my UI.

**Comment by Alarzzf** [comment]
Hi, can you just continue to support WA?
I don't want to use OmniCC.
Because using OmniCC will cause some problems with my UI.
