### ISSUE TITLE
Stuttering when triggering GCD. 2.11.5 #1197

### ISSUE THREAD

**Issue by devil81** [Afenar/AfenarUI#84]
I have same problem : https://www.youtube.com/watch?v=eQza4i9iEBo 

Im using DH pack and i will see if i get this on warlock aswell ... Happen only with 2.11.5 and 2.11.4 not with 2.11.3-20

**Comment by devil81** [comment]
it was wa problem . they fix it : Fix performance problems due to cooldown tracking

**Comment by Afenar** [comment]
It's wa addon issue, not my aura sets
