### ISSUE TITLE
Blood DK UI Missing Blood Boil Since September Update

### ISSUE THREAD

**Issue by charliegdev** [Afenar/AfenarUI#92]
Thank you for this awesome UI! I updated today and realized all versions from September 2020 (3.0.4-78) miss the Blood Boil icon:

<img width="655" alt="sep-update" src="https://user-images.githubusercontent.com/8703536/94284553-65714f00-ff07-11ea-9395-2e93c584530e.png">

As you can see, the icon for Blood Boil (4th one in the middle row) is blank. For reference, this is what the UI looks like from January 2020 (2.4.2-73):
<img width="659" alt="jan-update" src="https://user-images.githubusercontent.com/8703536/94284793-b7b27000-ff07-11ea-8aaa-3c4630bb1a00.png">

Thank you!

**Comment by Afenar** [comment]
it's not missing, this auras are for shadowlands, and there're bars for bb. there's no issue
