### ISSUE TITLE
Echoing reprimand animacharged number

### ISSUE THREAD

**Issue by Lihael** [Afenar/AfenarUI#95]
For Kyrian Rogue, there's no indication of which combo point was animacharged. I suggest these changes:

When a combo point is animacharged, its bar and background color should be changed.

If the number of combo points is exactly at the animacharged combo point, then it should change to another color. 

A text indicator on the echoing reprimand icon for the animacharged point.

**Comment by JamesMenetrey** [comment]
This has been addressed in the commit https://github.com/Afenar/AfenarUI/commit/a28174ac93d5c2928efe61fb3abd018958af64cb.

The combo point is highlighted and a number is given on the Kyrian's ability.
